import os
import re
import html
import asyncio
from pyrogram import Client, filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton


def txt_to_html(txt_path, html_path):
    # Read input file
    with open(txt_path, 'r', encoding='utf-8') as f:
        lines = f.read().splitlines()

    file_name = os.path.basename(txt_path).replace('.txt', '')

    # Categories
    sections = {
        'video': {"items": []},
        'pdf': {"items": []},
        'other': {"items": []}
    }

    # Function to categorize links
    def categorize(name, url):
        if (
            re.search(r'\.(mp4|mkv|avi|mov|flv|wmv|m3u8)$', url, re.IGNORECASE)
            or 'youtube.com' in url
            or 'youtu.be' in url
        ):
            return 'video'
        elif url.lower().endswith('.pdf'):
            return 'pdf'
        else:
            return 'other'

    # Extract name + URL lines
    for line in lines:
        line = line.strip()
        if not line:
            continue

        match = re.match(r'^(.*?)(https?://\S+)$', line)
        if not match:
            continue

        name, url = match.groups()
        cat = categorize(name, url)
        sections[cat]["items"].append((name.strip(), url.strip()))

    # Build HTML blocks
    html_blocks = ""

    for key in ['video', 'pdf', 'other']:
        links = []

        for name, url in sections[key]["items"]:
            safe_name = html.escape(name)
            if key == "video":
                links.append(f"<a href='{url}' target='_blank'><div class='video'>{safe_name}</div></a>")
            else:
                links.append(f"<a href='{url}' target='_blank'><div class='video'>{safe_name}</div></a>")

        content = "\n".join(links) if links else "<p>No content</p>"

        html_blocks += f"""
        <div class='tab-content' id='{key}' style='display:none;'>
            {content}
        </div>
        """

    # Final HTML template
    html_content = f"""
<!DOCTYPE html><html><head><meta charset='utf-8'>
<title>{html.escape(file_name)}</title>

<style>
body {{ background:#0a0a0a; color:#ffe3ec; font-family:'Segoe UI'; padding:20px }}
.video {{ padding:12px; margin-bottom:10px; border-left:4px solid #ff004f; background:#1c1c1c; border-radius:10px }}
.video:hover {{ background:#2a2a2a }}
.tab-button {{ padding:10px; margin:5px; background:#222; color:#fff; border-radius:8px; cursor:pointer }}
.tab-button.active {{ background:#ff004f; color:#000 }}
</style>

</head><body>

<div class="tabs">
    <button class="tab-button" onclick="showTab('video')">🎥 Videos</button>
    <button class="tab-button" onclick="showTab('pdf')">📜 PDFs</button>
    <button class="tab-button" onclick="showTab('other')">☠ Other</button>
</div>

{html_blocks}

<script>
function showTab(id) {{
    document.querySelectorAll('.tab-content').forEach(e => e.style.display = 'none');
    document.getElementById(id).style.display = 'block';
}}
document.addEventListener("DOMContentLoaded", () => showTab('video'));
</script>

</body></html>
"""

    # Write file
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html_content)

    return (
        len(sections["video"]["items"]),
        len(sections["pdf"]["items"]),
        len(sections["other"]["items"]),
    )


async def html_converter_callback(client, message):
    if not message.document or not message.document.file_name.endswith(".txt"):
        return await message.reply_text("⚠️ Please send a valid .txt file.")

    wait_msg = await message.reply_text("🕙 Converting TXT ➜ HTML... Please wait...")

    original_name = message.document.file_name
    base = os.path.splitext(original_name)[0].replace(" ", "_")

    txt_path = f"{base}.txt"
    html_path = f"{base}.html"

    # Download txt file
    await client.download_media(message.document, file_name=txt_path)

    # Convert
    video, pdf, other = txt_to_html(txt_path, html_path)

    caption = (
        f"📊 **Conversion Summary**\n\n"
        f"🎥 Videos: `{video}`\n"
        f"📜 PDFs: `{pdf}`\n"
        f"📁 Other: `{other}`\n\n"
        f"⚡ Generated by: **Lucifer's HTML Converter**"
    )

    # Send the HTML file
    await client.send_document(message.chat.id, html_path, caption=caption)

    # Remove wait message
    try:
        await wait_msg.delete()
    except:
        pass

    # Cleanup
    os.remove(txt_path)
    os.remove(html_path)
